Repository exercism/java-test-runner, pull requests merged in 2023-09, with the labels that each got.

#62 Always use version 3 in output JSON
  lib/src/main/java/com/exercism/report/Report.java
  lib/src/main/java/com/exercism/report/ReportGenerator.java
  tests/example-all-fail/expected_results.json
  tests/example-empty-file/expected_results.json
  tests/example-junit5/expected_results.json
  tests/example-partial-fail/expected_results.json
  tests/example-success-java17/expected_results.json
  tests/example-success/expected_results.json
  tests/example-syntax-error/expected_results.json
Labels: x:size/small

#38 Create dependabot.yml
  .github/dependabot.yml
Labels: x:size/tiny

#64 Never use status "error" when tests have been run
  lib/src/main/java/com/exercism/report/ReportGenerator.java
Labels: bug, x:size/small
